### PR TITLE
light tweaks

### PR DESCRIPTION
**Pull request by weptburrito**
Fixed dome emissive dimming
Brought in ASOBO code for dome light trying to make it do something else...fail lol

### CODE REVIEW

**Review by N95JPL — DISMISSED** [review]
Nice work, Pull Request Approved!

I will merge after my next commit (pending) which will be tomorrow!

**Review by N95JPL — APPROVED** [review]

**Review by N95JPL — APPROVED** [review]

**Comment by N95JPL** [comment]
Nice work!
There's a conflict somewhere due to a commit I made!
I can't merge via mobile app, so as soon as I am on the desktop I will fix and merge!
Thanks

**Comment by N95JPL** [comment]
I had to manually copy your scripting updates due to a "Conflict", which was an error on my behalf sorry!
Anyway, this was completed in Commit #d75bf8a (See Comment above)

Please could you download the latest push and just double check everything is okay please?

I will close this Pull Request & re-open a new one if needed!

**Comment by weptburrito** [comment]
Will do!

**Pull request closed without merging**
