### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by weptburrito**
***WARNING*** There are edits in the multiple panel.cfg files of all the planes that may mess up your side. Ignore these if necessary. Specifically the registration lines and the  texture line for the ADF.

Main update: All about the ADF. Between this and the last update, has been heavily modified.  Custom needle anim, this allows ANT mode test, "noise" from night effect and now distance. The whole stock system of active and standby has been thrown out the window due to lack of variables to have control. Instead of ADF1 active and standby, using ADF1 active and ADF2 as the standby. This gives needed control for state saving and for the actvie decimal auto tuning.

*.flt file tweaking. Some localvars removed or changed as other ways have presented themselves.
Some of the <Update> codes have been moved to another file just to organize things better. very WIP for my procrastinating OCD lol

Moved DME and AP to their own circuits using the right side breaks.  I looked at using "visibility code" to hide them but it left a hole in the panel, so I figure we just use as needed and inop the others?

New glass textures to check out??? Not squeaky clean, but just a hint of marks/scratches.

Added new instrument camera view that looks down between the seats to see the ipad and the fuel valve.

OH...this was in the last commit, maybe a new way to go on the copilot vis.  Since there doesn't seem to be a way to have this without having the weight in the flightmodel.cfg...I added and update code to set that station weight back to 0.  I've added back the old viz code for the pilot/copilot (slightly tweaked) So what happens now is we have control over the copilot viz, and its now technically back to 0 and NOT showing the copilot.  The downside is this, and ANY external weight changes really (fuel, pilots, cargo) do not reflect in the sims "Fuel" page. That's not just us, all third party planes trying to get al fancy suffer from the same thing, which is why they, and we, specify to make these changes in the EFB.

### CODE REVIEW

**Comment by weptburrito** [comment]
WT thing.  https://www.workingtitle.aero/packages/cj4/guides/repainter

Came across this awhile back, On our side we define a few different panel.cfg, in specific folders, with the different options a livery creator may want as the only reason for a livery to edit this file is for tailnumber color.  So with the folders panel.blackreg and panel.noreg (white is the default and therefore should not be included in a livery) the livery creator can then define their panel.cfg to only...example from my fairing livery panel.N2577E which has a painted on tail number

[fltsim]
alias=JPL_C152_Fairing\panel.noreg

And thats it. Thats all that they need. It will reference the one we set in the  panel.noreg folder

Point is that way if on our side we make any change to the panel.cfg, it doesn't break and future proofs the 3rd party liveries (assuming they incorporate this method) allieving the all to frequent comment "this doesn't work" with followed response "have you tried removing ALL other addons" 

Down side is we have remember to update ALL the panel.cfg (thats 3 per plane) ... that's where our issues come in...remembering to do that.

At this point TBH though, I don't think we should bother with it and remove this option. It does not seem to be commonplace and I think it may cause more issues than solutions. Plus when the plane development gets stabilized, no changes ever get made to that file anyway, its fairly set in stone.

**Comment by N95JPL** [comment]
That's a messy comment... I was typing whilst thinking... apologies 🤣

**Comment by weptburrito** [comment]
Oh you're good...I get it. I stuck those in months ago..but we haven't put an update out either so its not in the wild.

I only really thought about it again after your last updates with the taildragger plus with the changes in the efb made all those other cfgs I found were not updated (I don't think you knew they were there)   But yeah, if its possible to then have all of those then just alias one panel.cfg????....makes it all easier.

I'm actually sitting on an update, part of which includes some consolidation.  The whole sound.pck file is now in just one place, More adf upgrades plus a TON of things I need to get added in!!! 

I was starting to consolidate the texture files but ran into a problem and a deja vu.  Had some COMP files not building plus remembering you said something about blender adds these files into the folders??? Something with blender so I undid everything and figure wail til the model stuff stabilizes then look into that.

**Comment by N95JPL** [comment]
Yeah I possibly didn't realise/notice all of them, I think a base set of cfgs that everything refrences is the way forward there!

Oooo more ADF!?! Nice! and yes the Blender files add additional files, don't consolidate any of those files yet, I need to do that when the model calms down again - each model obviously has its own "special" files for specific parts but then, again, we will just ref. the base model for cockpit/base-fuselage files (That's a nasty little job).
The COMP files are a bit of a mine-field, I am hoping to write a script program which might automate consolidating all the texture files

I will merge this now too!

**Pull request merged**
